//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odevDagitimPortali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odev()
        {
            this.OdevKayit = new HashSet<OdevKayit>();
        }
    
        public int odevId { get; set; }
        public string odevAdi { get; set; }
        public string odevOzet { get; set; }
        public int odevDersId { get; set; }
    
        public virtual Ders Ders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdevKayit> OdevKayit { get; set; }
    }
}
