//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odevDagitimPortali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public int uyeId { get; set; }
        public string kullaniciAdi { get; set; }
        public string adSoyad { get; set; }
        public string sifre { get; set; }
        public string email { get; set; }
        public string uyeYetki { get; set; }
    }
}
